package Vista;
import Controlador.Controlador;
import static Modelo.Tarjeta.CATEGORIA;
import javax.swing.JOptionPane;

/*
 * Universidad Estatal a Distancia (UNED)
 * Cuatrimestre: I Cuatrimestre 2026
 * Proyecto: Proyecto 3 - Estructura de Datos
 * Descripción: Formulario Principal del sistema
 * Estudiante: Jose David Canizales Azocar
 * Fecha: Abril 2026
 */

public class GestionTarjetas extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestionTarjetas
     */
    
    private final Controlador controlador;
    
    public GestionTarjetas(Controlador controlador) {
        this.controlador = controlador;
        initComponents();
        cargarCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloVentana = new javax.swing.JLabel();
        tituloAgregarTarjetas = new javax.swing.JLabel();
        lblIdTarjeta = new javax.swing.JLabel();
        idTarjeta = new javax.swing.JTextField();
        lblCategoria = new javax.swing.JLabel();
        categoria = new javax.swing.JComboBox<>();
        lblDescripcion = new javax.swing.JLabel();
        descripcion = new javax.swing.JTextField();
        botonCancelar = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();
        separador1 = new javax.swing.JSeparator();
        tituloBuscarEliminar = new javax.swing.JLabel();
        idTarjetaBuscarEliminar = new javax.swing.JTextField();
        lblIdTarjeta1 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        separador2 = new javax.swing.JSeparator();
        tituloConsultas = new javax.swing.JLabel();
        botonPreorden = new javax.swing.JButton();
        botonInorden = new javax.swing.JButton();
        botonPostorden = new javax.swing.JButton();
        botonContar = new javax.swing.JButton();
        botonHojas = new javax.swing.JButton();
        botonMayorMenor = new javax.swing.JButton();
        botonConsultaAdicional = new javax.swing.JButton();
        separador3 = new javax.swing.JSeparator();
        tituloResultados = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoResultado = new javax.swing.JTextArea();
        separador4 = new javax.swing.JSeparator();
        tituloRepresentacionGrafica = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Gestion de Tarjetas");

        tituloVentana.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tituloVentana.setText("Gestion de Tarjetas");
        tituloVentana.setToolTipText("");

        tituloAgregarTarjetas.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tituloAgregarTarjetas.setText("Agregar tarjetas");
        tituloAgregarTarjetas.setToolTipText("");

        lblIdTarjeta.setText("ID");

        idTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTarjetaActionPerformed(evt);
            }
        });

        lblCategoria.setText("Categoria");

        lblDescripcion.setText("Nombre");

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        Agregar.setText("Registrar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        tituloBuscarEliminar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tituloBuscarEliminar.setText("Buscar / Eliminar");
        tituloBuscarEliminar.setToolTipText("");

        lblIdTarjeta1.setText("ID");

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        tituloConsultas.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tituloConsultas.setText("Consultas");
        tituloConsultas.setToolTipText("");

        botonPreorden.setText("Preorden");
        botonPreorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPreordenActionPerformed(evt);
            }
        });

        botonInorden.setText("Inorden");
        botonInorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInordenActionPerformed(evt);
            }
        });

        botonPostorden.setText("Postorden");
        botonPostorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPostordenActionPerformed(evt);
            }
        });

        botonContar.setText("Contar");
        botonContar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContarActionPerformed(evt);
            }
        });

        botonHojas.setText("Hojas");
        botonHojas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHojasActionPerformed(evt);
            }
        });

        botonMayorMenor.setText("Mayor / Menor");
        botonMayorMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMayorMenorActionPerformed(evt);
            }
        });

        botonConsultaAdicional.setText("Consulta Adicional");
        botonConsultaAdicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultaAdicionalActionPerformed(evt);
            }
        });

        tituloResultados.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tituloResultados.setText("Resultados");
        tituloResultados.setToolTipText("");

        textoResultado.setColumns(20);
        textoResultado.setRows(5);
        jScrollPane1.setViewportView(textoResultado);

        tituloRepresentacionGrafica.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tituloRepresentacionGrafica.setText("Representacion Grafica");
        tituloRepresentacionGrafica.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(tituloVentana)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloRepresentacionGrafica)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloConsultas)
                            .addComponent(tituloResultados))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(separador4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonMayorMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonConsultaAdicional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(botonPreorden, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonInorden, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonPostorden, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonContar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(separador1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIdTarjeta))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDescripcion)
                                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCategoria)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(categoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(separador2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tituloBuscarEliminar)
                                    .addComponent(tituloAgregarTarjetas))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(separador3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIdTarjeta1)
                                    .addComponent(idTarjetaBuscarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloVentana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloAgregarTarjetas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria)
                    .addComponent(lblIdTarjeta)
                    .addComponent(lblDescripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloBuscarEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIdTarjeta1)
                        .addGap(1, 1, 1)
                        .addComponent(idTarjetaBuscarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloConsultas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonPreorden)
                    .addComponent(botonInorden)
                    .addComponent(botonPostorden)
                    .addComponent(botonContar)
                    .addComponent(botonHojas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMayorMenor)
                    .addComponent(botonConsultaAdicional))
                .addGap(18, 18, 18)
                .addComponent(separador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloResultados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separador4, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloRepresentacionGrafica)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTarjetaActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        limpiarFormulario();
        // this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
       capturarDatosFormulario();
    }//GEN-LAST:event_AgregarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        capturarBusqueda();
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        capturarEliminacion();
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonPreordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPreordenActionPerformed
        mostrarPreorden();
    }//GEN-LAST:event_botonPreordenActionPerformed

    private void botonInordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInordenActionPerformed
        mostrarInorden();
    }//GEN-LAST:event_botonInordenActionPerformed

    private void botonPostordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPostordenActionPerformed
        mostrarPostorden();
    }//GEN-LAST:event_botonPostordenActionPerformed

    private void botonContarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContarActionPerformed
        mostrarConteoSuper();
    }//GEN-LAST:event_botonContarActionPerformed

    private void botonHojasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHojasActionPerformed
       mostrarHojasFrasesIconicas();
    }//GEN-LAST:event_botonHojasActionPerformed

    private void botonMayorMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMayorMenorActionPerformed
        mostrarMayorYMenor();
    }//GEN-LAST:event_botonMayorMenorActionPerformed

    private void botonConsultaAdicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultaAdicionalActionPerformed
        mostrarConsultaAdicional();
    }//GEN-LAST:event_botonConsultaAdicionalActionPerformed
 
    // ================ Metodos de Registro ================
    
    // Limpia todos los campos del formulario dejandolos en su estado inicial.
    private void limpiarFormulario() {
        this.idTarjeta.setText("");
        this.descripcion.setText("");
        this.categoria.setSelectedIndex(0);
        this.idTarjeta.requestFocus();
    }
    
    // Valida que los campos del formulario no esten vacios antes de registrar.
    private void validarCampos() {
        String id = this.idTarjeta.getText().trim();
        String descripcion = this.descripcion.getText().trim();
        String categoria = (String) this.categoria.getSelectedItem();

        if (id.isEmpty()) {
            throw new IllegalArgumentException("El campo Id es obligatorio.");
        }

        if (descripcion.isEmpty()) {
            throw new IllegalArgumentException("El campo Nombre es obligatorio.");
        }

        if (categoria == null || categoria.trim().isEmpty()) {
            throw new IllegalArgumentException("Debe seleccionar una categoria.");
        }
    }
    
    /**
     * Captura los datos del formulario, valida su formato e intenta
     * registrar la tarjeta.
    */
    private void capturarDatosFormulario() {
        try {
            // Validar los campos del formulario
            validarCampos();

            // Capturar los valores del formulario
            String idTexto = this.idTarjeta.getText().trim();
            String descripcionTexto = this.descripcion.getText().trim();
            String categoriaTexto = (String) this.categoria.getSelectedItem();

            // Intentar registrar la tarjeta
            controlador.agregarTarjeta(
                    idTexto,
                    descripcionTexto,
                    categoriaTexto
            );

            // Limpiar el formulario despues de registrar
            limpiarFormulario();

            // Mostrar mensaje en resultados
            textoResultado.setText("Tarjeta registrada correctamente.");

        } catch (IllegalArgumentException e) {
            // Mostrar mensaje de validacion
            JOptionPane.showMessageDialog(this, 
                e.getMessage(), 
                "Error de Validacion", 
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            // Mostrar error inesperado
            JOptionPane.showMessageDialog(this, 
                "Error inesperado: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // ================ Metodos de Busqueda y Eliminacion ================

    // Valida que el campo de busqueda y eliminacion no este vacio.
    private void validarIdBusquedaEliminacion() {
        String id = this.idTarjetaBuscarEliminar.getText().trim();

        if (id.isEmpty()) {
            throw new IllegalArgumentException("El campo Id es obligatorio.");
        }
    }

    // Captura el id, busca la tarjeta y muestra el resultado.
    private void capturarBusqueda() {
        try {
            // Validar el campo
            validarIdBusquedaEliminacion();

            // Capturar el id
            String idTexto = this.idTarjetaBuscarEliminar.getText().trim();

            // Buscar la tarjeta
            String resultado = controlador.buscarTarjeta(idTexto);

            // Mostrar resultado
            textoResultado.setText(resultado);

        } catch (IllegalArgumentException e) {
            // Mostrar error de validacion
            JOptionPane.showMessageDialog(this,
                    e.getMessage(),
                    "Error de Validacion",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            // Mostrar error inesperado
            JOptionPane.showMessageDialog(this,
                    "Error inesperado: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    // Captura el id, elimina la tarjeta y muestra el resultado.
    private void capturarEliminacion() {
        try {
            // Validar el campo
            validarIdBusquedaEliminacion();

            // Capturar el id
            String idTexto = this.idTarjetaBuscarEliminar.getText().trim();

            // Eliminar la tarjeta
            String resultado = controlador.eliminarTarjeta(idTexto);

            // Mostrar resultado
            textoResultado.setText(resultado);

        } catch (IllegalArgumentException e) {
            // Mostrar error de validacion
            JOptionPane.showMessageDialog(this,
                    e.getMessage(),
                    "Error de Validacion",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            // Mostrar error inesperado
            JOptionPane.showMessageDialog(this,
                    "Error inesperado: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // ================ Metodos de Consultas ================

    // Muestra el recorrido en preorden.
    private void mostrarPreorden() {
        try {
            // Obtener el recorrido
            String resultado = controlador.obtenerPreorden();

            // Mostrar resultado
            textoResultado.setText(resultado);

        } catch (Exception e) {
            // Mostrar error inesperado
            JOptionPane.showMessageDialog(this,
                    "Error inesperado: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    // Muestra el recorrido en inorden.
    private void mostrarInorden() {
        try {
            // Obtener el recorrido
            String resultado = controlador.obtenerInorden();

            // Mostrar resultado
            textoResultado.setText(resultado);

        } catch (Exception e) {
            // Mostrar error inesperado
            JOptionPane.showMessageDialog(this,
                    "Error inesperado: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    // Muestra el recorrido en postorden.
    private void mostrarPostorden() {
        try {
            // Obtener el recorrido
            String resultado = controlador.obtenerPostorden();

            // Mostrar resultado
            textoResultado.setText(resultado);

        } catch (Exception e) {
            // Mostrar error inesperado
            JOptionPane.showMessageDialog(this,
                    "Error inesperado: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // Muestra la cantidad de tarjetas de categorias super
    private void mostrarConteoSuper() {
        try {
            // Obtener el conteo
            String resultado = controlador.contarCategoriasSuper();

            // Mostrar resultado
            textoResultado.setText(resultado);

        } catch (Exception e) {
            // Mostrar error inesperado
            JOptionPane.showMessageDialog(this,
                    "Error inesperado: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // Muestra las hojas de la categoria frases iconicas.
    private void mostrarHojasFrasesIconicas() {
        try {
            // Obtener el resultado
            String resultado = controlador.listarFrasesIconicas();

            // Mostrar resultado
            textoResultado.setText(resultado);

        } catch (Exception e) {
            // Mostrar error inesperado
            JOptionPane.showMessageDialog(this,
                    "Error inesperado: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // Muestra la tarjeta menor y la tarjeta mayor.
    private void mostrarMayorYMenor() {
        try {
            // Obtener el resultado
            String resultado = controlador.obtenerMayorYMenor();

            // Mostrar resultado
            textoResultado.setText(resultado);

        } catch (Exception e) {
            // Mostrar error inesperado
            JOptionPane.showMessageDialog(this,
                    "Error inesperado: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // Metodo para la consulta adicional.
    private void mostrarConsultaAdicional() {
        try {
            // Obtener el resultado
            String resultado = controlador.obtenerConsultaAdicional();

            // Mostrar resultado
            textoResultado.setText(resultado);

        } catch (Exception e) {
            // Mostrar error inesperado
            JOptionPane.showMessageDialog(this,
                    "Error inesperado: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    // ================ Metodos Varios ================
    
    // Cargar categorias en el combobox
    private void cargarCategorias() {
        categoria.setModel(
            new javax.swing.DefaultComboBoxModel<>(
            CATEGORIA
        ));
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonConsultaAdicional;
    private javax.swing.JButton botonContar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonHojas;
    private javax.swing.JButton botonInorden;
    private javax.swing.JButton botonMayorMenor;
    private javax.swing.JButton botonPostorden;
    private javax.swing.JButton botonPreorden;
    private javax.swing.JComboBox<String> categoria;
    private javax.swing.JTextField descripcion;
    private javax.swing.JTextField idTarjeta;
    private javax.swing.JTextField idTarjetaBuscarEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblIdTarjeta;
    private javax.swing.JLabel lblIdTarjeta1;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSeparator separador3;
    private javax.swing.JSeparator separador4;
    private javax.swing.JTextArea textoResultado;
    private javax.swing.JLabel tituloAgregarTarjetas;
    private javax.swing.JLabel tituloBuscarEliminar;
    private javax.swing.JLabel tituloConsultas;
    private javax.swing.JLabel tituloRepresentacionGrafica;
    private javax.swing.JLabel tituloResultados;
    private javax.swing.JLabel tituloVentana;
    // End of variables declaration//GEN-END:variables
}
